apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: mariadb-dev
spec:
  providerConfigRef:
    name: default
  forProvider:
    chart:
      name: mariadb
      repository: https://charts.bitnami.com/bitnami
      version: "20.2.1"
    namespace: wordpress-dev
    values:
      image:
        tag: "latest"
      auth:
        rootPassword: rootpassword
        database: wordpress
        username: wordpress
        password: wordpresspassword
