apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: redis-staging
spec:
  providerConfigRef:
    name: default
  forProvider:
    chart:
      name: redis-staging
      repository: https://charts.bitnami.com/bitnami
      version: "20.6.3"
    namespace: wordpress
    values:
      image:
        tag: "latest"
      auth:
        enabled: false
      architecture: standalone
