apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: wordpress-staging
spec:
  providerConfigRef:
    name: default
  forProvider:
    chart:
      name: wordpress
      repository: https://charts.bitnami.com/bitnami
      version: "24.1.7"
    namespace: wordpress-staging
    values:
      image:
        tag: "latest"
      mariadb:
        enabled: true
        image:
          tag: "latest"
      wordpressUsername: admin
      wordpressPassword: stagingpassword
      service:
        type: ClusterIP
